name: PHP 7.4 Composer

on:
  push:
    branches: [ master ]

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        
    - name: Add HTTP basic auth credentials
      run: echo '${{ secrets.COMPOSER_AUTH_JSON_HTTP_BASIC }}' > $GITHUB_WORKSPACE/auth.json

    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        php_version: "7.4"
        php_extensions: curl json mbstring
        version: "2"
      
    - name: Remove auth.json file
      run: rm -f $GITHUB_WORKSPACE/auth.json